name: Reusable GitOps CI Maven Jib
on:
  workflow_call:
    inputs:
      dotenv-path:
        required: false
        type: string
        default: '.github/.env'
      always-publish:
        required: false
        type: boolean
        default: false
      always-scan:
        required: false
        type: boolean
        default: false
      ci-build-args:
        required: false
        type: string
        default: 'clean install'  
      java-version:
        required: false
        type: string
        default: '17'
      jib-from-image:
        required: false
        type: string
        default: 'eclipse-temurin:17-jre-jammy'
      jfrog-cli-version:
        required: false
        type: string
        default: 'latest'
      jfrog-ci-watch:
        required: false
        type: string
        default: 'ci-build-scan'
      jfrog-ci-fail:
        required: false
        type: boolean
        default: true
      sonar-qualitygate-wait:
        required: false
        type: boolean
        default: false
      sonar-scan-dir:
        required: false
        type: string
        default: 'target/classes'
      timeout-minutes:
        required: false
        type: number
        default: 30
    secrets:
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_API_KEY:
        required: true
      GITHUB_CI_APP_ID:
        required: true
      GITHUB_CI_APP_PRIVATE_KEY:
        required: true
      SONAR_TOKEN:
        required: true
      DT_TOKEN:
        required: false
env:
  DT_TOKEN: ${{ secrets.DT_TOKEN }}
  PUBLISH_IMAGE: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || inputs.always-publish }}
  SCAN_CODE: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'pull_request' || inputs.always-scan }}
jobs:
  build-and-test:
    timeout-minutes: ${{ inputs.timeout-minutes }}
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        #https://github.community/t/do-expressions-support-ternary-operators-to-change-their-returned-value/18114/4
        fetch-depth: ${{ fromJSON('["1", "0"]') [env.SCAN_CODE == 'true'] }}
    - name: Read Project Properties
      id: props
      uses: falti/dotenv-action@v1.0.4
      with:
        path: ${{ inputs.dotenv-path}}
        log-variables: true
    - name: Configure Workflow Environment
      id: config
      uses: mahajanatul525/github-actions-library/configure-workflow@master
      with:
        team: ${{ steps.props.outputs.team }}
        keysystem: ${{ steps.props.outputs.keysystem }}
        application-name: ${{ steps.props.outputs.application_name}} 
        docker-namespace: ${{ steps.props.outputs.docker_namespace }}
        artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }} 
        artifactory-api-key: ${{ secrets. ARTIFACTORY_API_KEY }}
        deployment-repo: ${{ steps.props.outputs.deployment_repo}}
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version}}
        cache: maven
    - name: Configure Maven Environment
      id: configure-maven
      uses: mahajanatul525/github-actions-library/configure-maven@master
      with:
        repository-base: ${{ steps.config.outputs.artifactory-base }}
        mirror-url: ${{ steps.config.outputs.maven-mirror-url}}
        release-url: ${{ steps.config.outputs.maven-release-url}}
        snapshot-url: ${{ steps.config.outputs.maven-snapshot-url}} 
        username: ${{ steps.config.outputs.artifactory-username}}
        password: ${{ steps.config.outputs.artifactory-api-key}}
    - name: Build & Test
      id: build-and-test
      run: | 
        mvn -B -V -e -Dstyle.color=always ${{ inputs.ci-build-args }} jib:dockerBuild \
        -Djib.container labels="keysystem=${{ steps.config.outputs.docker-label-keysystem }}, owner=${{ steps.config.outputs.docker-label-keysystem}}" \
        -Djib.from.image=${{ steps.config.outputs.docker-registry }}/${{ inputs.jib-from-image }} \
        -Djib.to.image ${{ steps.config.outputs.docker-snapshot-image-base}}:${{ steps.config.outputs.docker-sha-tag}}
    - name: Install JFrog CLI
      if: ${{ success() && env.SCAN_CODE == 'true'}}
      uses: jfrog/setup-jfrog-cli@v4.4.2
      with:
        version: ${{ inputs.jfrog-cli-version }}
    - name: JFrog Xray Vulnerability Scan
      id: xray-scan
      if: ${{success() && env.SCAN_CODE=='true'}}
      run: |
        export JFROG CLI_LOG_LEVEL DEBUG
        jf config add \
        --url=https://${{ steps.config.outputs.artifactory-base }}\ 
        --user=${{steps.config.outputs.artifactory-username}}\
        --password=${{ steps.config.outputs.artifactory-api-key}} \
        --interactive=false
        jf config show
        jf audit --watches=${{ inputs.jfrog-ci-watch}} --fail=${{ inputs.jfrog-ci-fail}} --mvn
        jf docker scan ${{steps.config.outputs.docker-snapshot-image-base}}: ${{steps.config.outputs.docker-sha-tag}} --watches=${{ inputs.jfrog-ci-watch}} --fail=${{inputs.jfrog-ci-fail}}
    - name: Cache SonarCloud packages
      if: ${{ success() && env.SCAN_CODE == 'true' }}
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
    - name: SonarCloud Compile
      if: ${{ success() && env.SCAN_CODE == 'true' }}
      env:
        GITHUB TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        pwd
        mvn -B -V -e ${{ inputs.ci-build-args }}
        ls -all
    - name: SonarCloud Scan
      id: sonarqube-scan
      if: ${{ success() && env.SCAN_CODE == 'true' }}
      uses: sonarsource/sonarqube-scan-action@v3.0.0
      env:
        GITHUB TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
      with:
        args: >
          -Dsonar.organization=mydomain-insurance-na
          -Dsonar.projectKey=mydomain-Insurance-NA_${{ steps.props.outputs.team }}-${{ steps.props.outputs.application_name}} 
          -Dsonar.projectName=${{ steps.props.outputs.team }}-${{ steps.props.outputs.application_name }}
          -Dsonar.qualitygate.wait=${{ inputs.sonar-qualitygate-wait }}
          -Dsonar.java.binaries=${{ inputs.sonar-scan-dir}}

    - name: Publish Image
      if: ${{ success() && env.PUBLISH_IMAGE == 'true'}}
      id: publish-image
      env:
        SKOPEO ARGS: --src-creds ${{ steps.config.outputs.artifactory-username }}:${{ steps.config.outputs.artifactory-api-key}} --dest-creds ${{steps.config.outputs.artifactory-username }}:${{ steps.config.outputs.artifactory-api-key }} 
        DOCKER SNAPSHOT_SHA_TAG: ${{ steps.config.outputs.docker-snapshot-image-base }}:${{ steps.config.outputs.docker-sha-tag}}
        DOCKER SNAPSHOT_REF_TAG: ${{ steps.config.outputs.docker-snapshot-image-base }}:${{ steps.config.outputs.docker-ref-tag }}
        DOCKER SNAPSHOT BUILD_TAG: ${{ steps.config.outputs.docker-snapshot-image-base }}:${{ steps.config.outputs.docker-build-tag}}
      run: |
        skopeo copy docker-daemon: $DOCKER_SNAPSHOT_SHA_TAG docker://$DOCKER_SNAPSHOT_SHA_TAG $SKOPEO ARGS
        skopeo copy docker://SDOCKER_SNAPSHOT_SHA_TAG docker://$DOCKER_SNAPSHOT_REF_TAG $SKOPEO_ARGS
        skopeo copy docker://SDOCKER_SNAPSHOT_SHA_TAG docker://SDOCKER_SNAPSHOT_BUILD_TAG $SKOPEO_ARGS
    - name: Generate Deployment Token
      if: ${{ success() && env.PUBLISH_IMAGE=='true' }}
      uses: tibdex/github-app-token@v2
      id: generate-deployment-token
      with:
        app_id: ${{ secrets.GITHUB_CI_APP_ID}}
        private key: ${{ secrets.GITHUB_CI_APP_PRIVATE_KEY }}
        repository: ${{ steps.props.outputs.deployment_repo}}
    - name: Notify Deployment Repository
      if: ${{ success() && env.PUBLISH_IMAGE == 'true'}}
      uses: peter-evans/repository-dispatch@v2
      id: notify-deployment-repository
      with:
        repository: ${{ steps.props.outputs.deployment_repo}}
        token: ${{ steps.generate-deployment-token.outputs.token }}
        event-type: ci-notification
        client-payload: |
          {
            "github": {
              "team": "${{ steps.props.outputs.team }}",
              "application-name": "${{ steps.props.outputs.application_name}}",
              "repository": "${{ github.repository }}",
              "ref": "${{ github.ref }}"
            }, 
            "image": {
              "base": "${{ steps.config.outputs.docker-snapshot-image-base }}"
              "ref_tag": "${{steps.config.outputs.docker-ref-tag}}",
              "sha_tag": "${{steps.config.outputs.docker-sha-tag}}",
              "build_tag": "${{ steps.config.outputs.docker-build-tag}}"
            }
          }
